### ISSUE TITLE
Test motion for move arm to bin fails

### ISSUE THREAD

**Issue by yuyu2172** [start-jsk/jsk_apc#1374] opened 2016-04-30 01:22 UTC
Test added at #1367 is failing.
https://travis-ci.org/start-jsk/jsk_apc/builds/126795825

I tried, but I could not fix it right away.

**Comment by wkentaro** [comment] 2016-04-30 01:34
```

                                                                                
[jsk_2015_05_baxter_apc:cmake] CMake Error at /opt/ros/indigo/share/catkin/cmake/test/tests.cmake:128 (add_custom_target):



                                                                                
[jsk_2015_05_baxter_apc:cmake]   add_custom_target called with invalid target name



                                                                                
[jsk_2015_05_baxter_apc:cmake]   "run_tests_jsk_2015_05_baxter_apc_shell-test_roseus_/workspace/ros/ws_jsk_apc/src/jsk_apc/jsk_2015_05_baxter_apc/euslisp/test/test-move-arm-to-bin.l".



                                                                                
[jsk_2015_05_baxter_apc:cmake]   Target names may not contain a slash.  Use ADD_CUSTOM_COMMAND to generate



                                                                                
```
It seems that jsk_common is old. the new released jsk_common should fix this problem. So please just restart the job.

**Comment by yuyu2172** [comment] 2016-04-30 01:40
@wkentaro 
Thanks. I will restart it and see how it goes.

**Comment by yuyu2172** [comment] 2016-04-30 02:40
@wkentaro 
Travis remains to fail after restarting. 
FYI, the test passed after updating jsk_common, on my local setting, 

Should I wait longer?

**Comment by wkentaro** [comment] 2016-04-30 02:41
Why fails?

--
和田 健太郎 / Kentaro Wada
http://wkentaro.com/

2016年4月30日 11:40 +0900 に Yusuke Niitani<notifications@github.com>は書きました:

**Comment by yuyu2172** [comment] 2016-04-30 02:49
```
11:31:32 jsk_2015_05_baxter_apc/test_results/jsk_2015_05_baxter_apc/MISSING-shell-test_roseus__workspace_ros_ws_jsk_apc_src_jsk_apc_jsk_2015_05_baxter_apc_euslisp_test_test-move-arm-to-bin.l.xml: 1 tests, 0 errors, 1 failures
```

**Comment by wkentaro** [comment] 2016-04-30 03:23
Thanks, I found the cause of this bug.
```
[jsk_2015_05_baxter_apc:make] /bin/sh: 1: /opt/ros/indigo/share/jsk_tools/cmake/run_shell_test.py: not found
```
It should be fixed via https://github.com/jsk-ros-pkg/jsk_common/pull/1385 . 
Hotfix is https://github.com/start-jsk/jsk_apc/pull/1375

**Comment by yuyu2172** [comment] 2016-04-30 03:26
Cool! Thanks for the fixes.

**Comment by wkentaro** [comment] 2016-04-30 03:27
Sorry for the bug :pensive:

**Comment by wkentaro** [comment] 2016-04-30 03:51
Closed via #1375

**Comment by wkentaro** [comment] 2016-04-30 03:52
@yuyu2172 Please rebase in your PRs.

**Closed by wkentaro** 2016-04-30 03:51 UTC
Labels: bug, test

**Comment by yuyu2172** [comment] 2016-04-30 04:56
That is why it didn't work! Thanks
